version: '3.7'
services:
  postgres:
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=roomsUser
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5438:5432'
volumes:
  postgres: