export default {
	unknown_error: 'Unknown error occurred',
	description: 'Description',
	cancel: 'Cancel',
	submit: 'Submit',
	sk: 'Slovak',
	en: 'English',
	home: 'Home',
	about: 'About',
	login: 'Login',
	logout: 'Logout',
	delete: 'Delete',
	required: 'Required',
	name: 'Name',
	location: 'Location',
	ppd: 'Price per day in CZK',
	email: 'Email',
	password: 'Password',
	search: 'Search',
	from: 'Start date',
	to: 'End date',
	orderBy: 'Order By'
};
