export default {
	introductionFirstLine:
		'Looking for saving some buck and renting room from locals?',
	introductionSecondLine:
		' Are you living in	Brno or Prague and want to cut the middle man and share?',
	introductionThirdLine: 'Then wait no longer and join our site!',
	unknown_error: 'Unknown error occurred',
	description: 'Description',
	cancel: 'Cancel',
	submit: 'Submit',
	sk: 'Slovak',
	en: 'English',
	home: 'Home',
	about: 'About',
	login: 'Log in',
	loginButtonText: 'Log in',
	logout: 'Log out',
	delete: 'Delete',
	required: 'Required',
	name: 'Name',
	location: 'Location',
	ppd: 'Price per night in CZK',
	imageUrl: 'Image URL',
	imageLabel: 'Image label',
	email: 'Email',
	password: 'Password',
	search: 'Search',
	from: 'Start date',
	to: 'End date',
	orderBy: 'Order By',
	price: 'Price',
	addRoom: 'Add room',
	searchRooms: 'Search rooms',
	myRooms: 'My rooms',
	myReservations: 'My reservations',
	signUp: 'Sign up',
	signUpButtonText: 'Sign up',
	brno: 'Brno',
	prague: 'Prague',
	priceAsc: 'price (ascending)',
	priceDesc: 'price (descending)',
	locationAsc: 'location (ascending)',
	locationDesc: 'location (descending)',
	welcome: 'Welcome',
	invalidEmail: 'Invalid email!',
	passwordShort: 'Password too short! (Under 8 characters)',
	passwordLong: 'Password too long! (Over 16 characters)',
	invalidName: 'Invalid name!',
	nameShort: 'Name too short! (Under 3 characters)',
	nameLong: 'Name too long! (Over 15 characters)',
	title: 'Airbnb rooms',
	loginFailed: 'Login failed!',
	signUpFailed: 'Sign up failed!'
};
