export default {
	introductionFirstLine:
		'Chcete ušetriť peniaze a prenajať si izbu priamo od miestnych?',
	introductionSecondLine:
		'Žijete v Brne alebo v Prahe a chcete sa zbaviť sprostredkovatela?',
	introductionThirdLine: 'Tak neváhajte a vyskúšajte si našu stránku!',
	unknown_error: 'Neznámy error',
	description: 'Popis',
	cancel: 'Zrušiť',
	submit: 'Potvrdiť',
	sk: 'Slovenčina',
	en: 'Angličtina',
	home: 'Domov',
	login: 'Prihlásenie',
	loginButtonText: 'Prihlásiť sa',
	logout: 'Odhlásenie',
	delete: 'Zmaž',
	required: 'Povinné',
	name: 'Názov',
	location: 'Lokácia',
	ppd: 'Cena za noc v CZK',
	imageUrl: 'URL obrázku',
	imageLabel: 'Popis obrázku',
	email: 'Email',
	password: 'Heslo',
	search: 'Vyhladať',
	from: 'Od dátumu',
	to: 'Po dátum',
	orderBy: 'Usporiadat podľa',
	price: 'Cena',
	addRoom: 'Pridať izbu',
	searchRooms: 'Hľadať izbu',
	myRooms: 'Moje izby',
	myReservations: 'Moje rezervácie',
	signUp: 'Registrácia',
	signUpButtonText: 'Zaregistrovať sa',
	brno: 'Brno',
	prague: 'Praha',
	priceAsc: 'cena (vzostupne)',
	priceDesc: 'cena (zostupne)',
	locationAsc: 'lokácia (vzostupne)',
	locationDesc: 'lokácia (zostupne)',
	welcome: 'Vitaj',
	invalidEmail: 'Neplatný email!',
	passwordShort: 'Heslo je príliš krátke! (Menej ako 8 znakov)',
	passwordLong: 'Heslo je príliš krátke! (Viac ako 16 znakov)',
	invalidName: 'Neplatné meno!',
	nameShort: 'Meno je príliš krátke! (Menej ako 3 znaky)',
	nameLong: 'Meno je príliš dlhé! (Viac ako 15 znakov)',
	title: 'Airbnb izby'
};
