export default {
	unknown_error: 'Neznámy error',
	description: 'Popis',
	cancel: 'Zrušiť',
	submit: 'Potvrdiť',
	sk: 'Slovenčina',
	en: 'Angličtina',
	home: 'Domov',
	login: 'Prihlásenie',
	logout: 'Odhlásenie',
	delete: 'Zmaž',
	required: 'Povinné',
	name: 'Názov',
	location: 'Lokácia',
	ppd: 'Cena za deň v CZK',
	email: 'Email',
	password: 'Heslo',
	search: 'Vyhladať',
	from: 'Od dátumu',
	to: 'Po dátum',
	orderBy: 'Usporiadat podľa',
	price: 'Cena'
};
